"""Add structured findings tables

Revision ID: 562b70d02351
Revises: 440e57b541d7
Create Date: 2026-01-17 21:26:53.171892

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '562b70d02351'
down_revision = '440e57b541d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_generated_findings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('ai_test_result_id', sa.Integer(), nullable=True),
    sa.Column('liver_size', sa.String(length=20), nullable=True),
    sa.Column('liver_texture', sa.String(length=20), nullable=True),
    sa.Column('liver_focal_defect', sa.String(length=20), nullable=True),
    sa.Column('liver_cbd', sa.String(length=20), nullable=True),
    sa.Column('liver_pv', sa.String(length=20), nullable=True),
    sa.Column('spleen_size', sa.String(length=20), nullable=True),
    sa.Column('spleen_focal_defect', sa.String(length=20), nullable=True),
    sa.Column('gb_calculus', sa.String(length=20), nullable=True),
    sa.Column('gb_wall_edema', sa.String(length=20), nullable=True),
    sa.Column('right_kidney_size', sa.String(length=20), nullable=True),
    sa.Column('right_kidney_texture', sa.String(length=20), nullable=True),
    sa.Column('right_kidney_other', sa.String(length=200), nullable=True),
    sa.Column('left_kidney_size', sa.String(length=20), nullable=True),
    sa.Column('left_kidney_texture', sa.String(length=20), nullable=True),
    sa.Column('left_kidney_other', sa.String(length=200), nullable=True),
    sa.Column('pancreas_findings', sa.Text(), nullable=True),
    sa.Column('bladder_filling', sa.String(length=20), nullable=True),
    sa.Column('bladder_stone_mass', sa.String(length=20), nullable=True),
    sa.Column('bladder_mucosal_irregularity', sa.String(length=20), nullable=True),
    sa.Column('prostate_findings', sa.Text(), nullable=True),
    sa.Column('ascites', sa.String(length=20), nullable=True),
    sa.Column('pleural_effusions', sa.String(length=20), nullable=True),
    sa.Column('para_aortic_lymph_nodes', sa.String(length=20), nullable=True),
    sa.Column('other_findings', sa.String(length=200), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('confidence_scores', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ai_test_result_id'], ['ai_test_results.id'], ),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('structured_findings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('liver_size', sa.String(length=20), nullable=True),
    sa.Column('liver_texture', sa.String(length=20), nullable=True),
    sa.Column('liver_focal_defect', sa.String(length=20), nullable=True),
    sa.Column('liver_cbd', sa.String(length=20), nullable=True),
    sa.Column('liver_pv', sa.String(length=20), nullable=True),
    sa.Column('spleen_size', sa.String(length=20), nullable=True),
    sa.Column('spleen_focal_defect', sa.String(length=20), nullable=True),
    sa.Column('gb_calculus', sa.String(length=20), nullable=True),
    sa.Column('gb_wall_edema', sa.String(length=20), nullable=True),
    sa.Column('right_kidney_size', sa.String(length=20), nullable=True),
    sa.Column('right_kidney_texture', sa.String(length=20), nullable=True),
    sa.Column('right_kidney_other', sa.String(length=200), nullable=True),
    sa.Column('left_kidney_size', sa.String(length=20), nullable=True),
    sa.Column('left_kidney_texture', sa.String(length=20), nullable=True),
    sa.Column('left_kidney_other', sa.String(length=200), nullable=True),
    sa.Column('pancreas_findings', sa.Text(), nullable=True),
    sa.Column('bladder_filling', sa.String(length=20), nullable=True),
    sa.Column('bladder_stone_mass', sa.String(length=20), nullable=True),
    sa.Column('bladder_mucosal_irregularity', sa.String(length=20), nullable=True),
    sa.Column('prostate_findings', sa.Text(), nullable=True),
    sa.Column('ascites', sa.String(length=20), nullable=True),
    sa.Column('pleural_effusions', sa.String(length=20), nullable=True),
    sa.Column('para_aortic_lymph_nodes', sa.String(length=20), nullable=True),
    sa.Column('other_findings', sa.String(length=200), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('case_id')
    )
    op.create_table('findings_evaluations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ai_finding_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('field_correctness', sa.JSON(), nullable=False),
    sa.Column('total_fields', sa.Integer(), nullable=True),
    sa.Column('correct_fields', sa.Integer(), nullable=True),
    sa.Column('accuracy_percentage', sa.Float(), nullable=True),
    sa.Column('evaluation_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ai_finding_id'], ['ai_generated_findings.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('findings_evaluations')
    op.drop_table('structured_findings')
    op.drop_table('ai_generated_findings')
    # ### end Alembic commands ###
