"""Add CaseImage model for multiple images per case

Revision ID: 75467a6542af
Revises: 1548dbecdf98
Create Date: 2025-11-05 15:35:00.700873

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75467a6542af'
down_revision = '1548dbecdf98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('case_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('image_path', sa.String(length=500), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('mime_type', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cases', schema=None) as batch_op:
        batch_op.alter_column('image_filename',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('image_path',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cases', schema=None) as batch_op:
        batch_op.alter_column('image_path',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
        batch_op.alter_column('image_filename',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)

    op.drop_table('case_images')
    # ### end Alembic commands ###
