"""Add AITestResult model for saving AI testing reports

Revision ID: d7d91502e48f
Revises: 75467a6542af
Create Date: 2026-01-06 13:44:04.464953

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7d91502e48f'
down_revision = '75467a6542af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_test_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('saved_filename', sa.String(length=255), nullable=False),
    sa.Column('image_path', sa.String(length=500), nullable=False),
    sa.Column('view_type', sa.String(length=100), nullable=True),
    sa.Column('image_context', sa.Text(), nullable=True),
    sa.Column('expected_pathology', sa.String(length=255), nullable=True),
    sa.Column('ai_analysis', sa.Text(), nullable=False),
    sa.Column('raw_response', sa.JSON(), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('mime_type', sa.String(length=50), nullable=True),
    sa.Column('accuracy_rating', sa.Integer(), nullable=True),
    sa.Column('completeness_rating', sa.Integer(), nullable=True),
    sa.Column('terminology_rating', sa.Integer(), nullable=True),
    sa.Column('overall_rating', sa.Integer(), nullable=True),
    sa.Column('ai_identified_pathology', sa.String(length=255), nullable=True),
    sa.Column('evaluation_comments', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ai_test_results')
    # ### end Alembic commands ###
